import { useState, useEffect } from 'react';
import useSWR from 'swr';
import Head from 'next/head';
import Image from 'next/image';
import { Inter } from 'next/font/google';
import styles from '@/styles/Home.module.css';

const fetcher = (...args) => fetch(...args).then((res) => res.json());

export default function Home() {
  const [message, setMessage] = useState('');
  const [chaco, setChaco] = useState(0);

  const handleChange = (event) => {
    setMessage(event.target.value);
  };

  const handleClick = () => {
    setChaco(message);
    setMessage('');
  };

  const { data, error, isLoading } = useSWR(
    `/api/hello?value1=${chaco}`,
    fetcher
  );

  // useEffect(() => {
  //   setLoading(true);
  //   fetch('/api/hello')
  //     .then((res) => res.json())
  //     .then((data) => {
  //       setData(data);

  //       setLoading(false);
  //     });
  // }, []);

  if (error) return <div>Failed to load</div>;
  if (isLoading) return <div>loading...</div>;

  return (
    <>
      <Head>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className={styles.main}>
        {data.name}
        <input
          type='text'
          id='message'
          name='message'
          onChange={handleChange}
          value={message}
        />
        <button onClick={handleClick}>Envoyer</button>
      </main>
    </>
  );
}
